services:
  mongo:
    image: mongo:8
    container_name: banexcoin.mongo
    ports:
      - '27017:27017'
    networks:
      - banexcoin-network

  ai:
    build:
      context: ./apps/api/ai
      dockerfile: Dockerfile
    container_name: banexcoin.ai
    ports:
      - '8081:8080'
    volumes:
      - ./.containers/ai-data:/app/data
    networks:
      - banexcoin-network

networks:
  banexcoin-network:
    name: banexcoin-network
